package org.usfirst.frc2079.Java.subsystems;

import org.usfirst.frc2079.Java.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid;

public class Climb extends Subsystem {

    private final Compressor compressor = RobotMap.compressor;
    private final DoubleSolenoid dsClawLift = RobotMap.dsClawTilt;
    private final Solenoid dsClawDeploy = RobotMap.dsClawDeploy;

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {

    }
}

